enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  styled-components@*:
    dependencies:
      react-is: ^18.2.0

pnpMode: strict

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.6.0.cjs
