yarnPath: .yarn/releases/yarn-4.5.3.cjs
nodeLinker: pnp
supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
    - "win32"

  cpu:
    - "current"
    - "x86"
    - "x64"
    - "arm64"
    - "ia32"
pnpMode: strict
enableGlobalCache: false
packageExtensions:
  "styled-components@*":
    dependencies:
      "react-is": "^18.2.0"